//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectAvanzada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA_VENDEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIA_VENDEDOR()
        {
            this.VENDEDORs = new HashSet<VENDEDOR>();
        }
    
        public int IDCATEGORIA { get; set; }
        public int IDSALARIO { get; set; }
    
        public virtual SALARIO SALARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENDEDOR> VENDEDORs { get; set; }
    }
}
