//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectAvanzada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public int IDINVENTARIO { get; set; }
        public int IDPRODUCTO { get; set; }
        public int CANTIDAD_COMPRADA { get; set; }
        public int STOCK { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
